# settings
title: Le Crochet d'Argent
email: contact@lecrochetdargent.fr
description: Réalisations au tricot et crochet
baseurl: ""
url: "https://www.lecrochetdargent.fr"
default_bg: /assets/images/logo-big.png

# for facebook instant article

author:
  name     : 'Hélène'
  email    : contact@lecrochetdargent.fr
  url      : https://www.lecrochetdargent.fr
  facebook : http://facebook.com/Le-crochet-dargent-456929781182767
  twitter  : http://twitter.com/crochetdargent
  mastodon : https://framapiaf.org/@crochetdargent
  avatar   : /assets/images/logo.png

github: https://github.com/nandomoreirame/zetsu
disqus_shortname: "le-crochet-dargent"
google_analytics: UA-100414652-1
facebookapps_id: 1617415464944797

# jekyll-paginate
#paginate: 5
#paginate_path: "/page/:num"
# octopress-paginate
pagination:
  per_page: 5
  limit: false
  permalink: "/page/:num"

comments: true

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
excerpt_separator: "<!--more-->"
plugins: 
  - octopress-paginate
  - jekyll-feed
  - jekyll-responsive-image
  - jekyll/figure
  - jekyll-sitemap
  - jekyll-polyglot

languages: ["fr", "en"]
default_lang: "fr"
exclude_from_localization: ["javascript", "images", "css", "assets"]
parallel_localization: true

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

responsive_image:
  # [Required]
  # Path to the image template.
  template: _includes/responsive-image.html

  # [Optional, Default: 85]
  # Quality to use when resizing images.
  default_quality: 90

  # [Optional, Default: []]
  # An array of resize configuration objects. Each object must contain at least
  # a `width` value.
  sizes:
    - width: 160  # [Required] How wide the resized image will be.
      quality: 70 # [Optional] Overrides default_quality for this size.
    - width: 480  # [Required] How wide the resized image will be.
      quality: 80 # [Optional] Overrides default_quality for this size.
    - width: 800
      quality: 90
    - width: 1600
      quality: 95

  # [Optional, Default: false]
  # Rotate resized images depending on their EXIF rotation attribute. Useful for
  # working with JPGs directly from digital cameras and smartphones
  auto_rotate: false

  # [Optional, Default: assets]
  # The base directory where assets are stored. This is used to determine the
  # `dirname` value in `output_path_format` below.
  base_path: assets/images

  # [Optional, Default: assets/resized/%{filename}-%{width}x%{height}.%{extension}]
  # The template used when generating filenames for resized images. Must be a
  # relative path.
  #
  # Parameters available are:
  #   %{dirname}     Directory of the file relative to `base_path` (assets/sub/dir/some-file.jpg => sub/dir)
  #   %{basename}    Basename of the file (assets/some-file.jpg => some-file.jpg)
  #   %{filename}    Basename without the extension (assets/some-file.jpg => some-file)
  #   %{extension}   Extension of the file (assets/some-file.jpg => jpg)
  #   %{width}       Width of the resized image
  #   %{height}      Height of the resized image
  #
  output_path_format: assets/resized/%{dirname}/%{filename}-%{width}x%{height}.%{extension}

  # [Optional, Default: []]
  # By default, only images referenced by the responsive_image and responsive_image_block
  # tags are resized. Here you can set a list of paths or path globs to resize other
  # images. This is useful for resizing images which will be referenced from stylesheets.
  extra_images:
    - assets/images/*/*

